// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const sendMessage = `-- name: SendMessage :one
INSERT INTO messages (sender_id, body, sent_at, hostname, port)
VALUES (
    $1,
    $2,
    NOW(),
    $3, 
    $4
)
RETURNING sender_id, body, sent_at, hostname, port
`

type SendMessageParams struct {
	SenderID uuid.UUID
	Body     string
	Hostname string
	Port     string
}

func (q *Queries) SendMessage(ctx context.Context, arg SendMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, sendMessage,
		arg.SenderID,
		arg.Body,
		arg.Hostname,
		arg.Port,
	)
	var i Message
	err := row.Scan(
		&i.SenderID,
		&i.Body,
		&i.SentAt,
		&i.Hostname,
		&i.Port,
	)
	return i, err
}
