// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkPassword = `-- name: CheckPassword :one
SELECT id, username, created_at, updated_at, nickname
FROM users
WHERE password = $1
`

type CheckPasswordRow struct {
	ID        uuid.UUID
	Username  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Nickname  string
}

func (q *Queries) CheckPassword(ctx context.Context, password []byte) (CheckPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, checkPassword, password)
	var i CheckPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Nickname,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, username, password, nickname)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1, 
    $2,
    NULL
)
RETURNING id, created_at, updated_at, username, password, nickname
`

type CreateUserParams struct {
	Username string
	Password []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Password,
		&i.Nickname,
	)
	return i, err
}

const findID = `-- name: FindID :one
SELECT id
FROM users
WHERE username = $1
`

func (q *Queries) FindID(ctx context.Context, username string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, findID, username)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT username, password, nickname
FROM users
WHERE id = $1
`

type FindUserByIDRow struct {
	Username string
	Password []byte
	Nickname string
}

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (FindUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(&i.Username, &i.Password, &i.Nickname)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, password, nickname
FROM users
WHERE username = $1
`

type FindUserByUsernameRow struct {
	ID       uuid.UUID
	Password []byte
	Nickname string
}

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (FindUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, findUserByUsername, username)
	var i FindUserByUsernameRow
	err := row.Scan(&i.ID, &i.Password, &i.Nickname)
	return i, err
}

const setNickname = `-- name: SetNickname :one
UPDATE users
SET nickname = $1
WHERE id = $2
RETURNING id, created_at, updated_at, username, password, nickname
`

type SetNicknameParams struct {
	Nickname string
	ID       uuid.UUID
}

func (q *Queries) SetNickname(ctx context.Context, arg SetNicknameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setNickname, arg.Nickname, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Password,
		&i.Nickname,
	)
	return i, err
}
